"""Build ml_model.ipynb — end-to-end ML pipeline for product recommendation."""
import json, os

def md(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}

def code(lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": lines}

cells = [

md(["# CIC6314 — Smart Product Recommendation System\n",
    "**Member 3 — ML module**\n",
    "Dataset: UCI Online Retail | Model: ALS (Alternating Least Squares)\n"]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 1. Load Data\n"]),

code([
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import pickle\n",
    "import os\n",
    "import sys\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "if os.path.basename(os.getcwd()) == 'notebooks':\n",
    "    os.chdir('..')\n",
    "if os.getcwd() not in sys.path:\n",
    "    sys.path.insert(0, os.getcwd())\n",
    "\n",
    "df_raw = pd.read_excel('data/online+retail/Online Retail.xlsx')\n",
    "print('Shape:', df_raw.shape)\n",
    "df_raw.head()\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 2. EDA\n",
    "Explore the dataset before doing anything to it.\n"]),

code([
    "# basic info\n",
    "print(df_raw.dtypes)\n",
    "print()\n",
    "print(df_raw.describe())\n",
]),

code([
    "# check missing values\n",
    "print('Missing values:')\n",
    "print(df_raw.isnull().sum())\n",
    "# CustomerID has a lot of nulls - those are guest checkouts\n",
]),

code([
    "# how many unique customers and products\n",
    "print('Unique customers:', df_raw['CustomerID'].nunique())\n",
    "print('Unique products:', df_raw['StockCode'].nunique())\n",
    "print('Unique countries:', df_raw['Country'].nunique())\n",
    "print('Date range:', df_raw['InvoiceDate'].min(), 'to', df_raw['InvoiceDate'].max())\n",
]),

code([
    "# check for cancelled orders - invoices starting with C\n",
    "cancelled = df_raw[df_raw['InvoiceNo'].astype(str).str.startswith('C')]\n",
    "print('Cancelled rows:', len(cancelled))\n",
    "print('Normal rows:', len(df_raw) - len(cancelled))\n",
]),

code([
    "# quantity distribution - are there negatives?\n",
    "print('Quantity stats:')\n",
    "print(df_raw['Quantity'].describe())\n",
    "print('Negative quantity rows:', (df_raw['Quantity'] < 0).sum())\n",
    "print('Zero price rows:', (df_raw['UnitPrice'] == 0).sum())\n",
]),

code([
    "# sales over time\n",
    "df_raw['InvoiceDate'] = pd.to_datetime(df_raw['InvoiceDate'])\n",
    "df_raw['Month'] = df_raw['InvoiceDate'].dt.to_period('M')\n",
    "monthly = df_raw.groupby('Month')['Quantity'].sum()\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "monthly.plot(kind='bar', color='steelblue')\n",
    "plt.title('Monthly Sales Volume')\n",
    "plt.xlabel('Month')\n",
    "plt.ylabel('Total Quantity Sold')\n",
    "plt.xticks(rotation=45)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]),

code([
    "# top 10 most purchased products\n",
    "top_products = df_raw.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)\n",
    "print('Top 10 products:')\n",
    "print(top_products)\n",
]),

code([
    "# top 10 countries by number of orders\n",
    "top_countries = df_raw['Country'].value_counts().head(10)\n",
    "plt.figure(figsize=(8, 4))\n",
    "top_countries.plot(kind='bar', color='coral')\n",
    "plt.title('Top 10 Countries by Orders')\n",
    "plt.xticks(rotation=45)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]),

code([
    "# how many products does the average customer buy?\n",
    "items_per_customer = df_raw.groupby('CustomerID')['StockCode'].nunique()\n",
    "print('Products per customer:')\n",
    "print(items_per_customer.describe())\n",
    "\n",
    "plt.figure(figsize=(8, 4))\n",
    "plt.hist(items_per_customer, bins=50, color='green', edgecolor='white')\n",
    "plt.title('Distribution of Unique Products per Customer')\n",
    "plt.xlabel('Number of unique products')\n",
    "plt.ylabel('Number of customers')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 3. Data Cleaning\n",
    "Remove bad rows found in EDA.\n"]),

code([
    "df = df_raw.copy()\n",
    "\n",
    "before = len(df)\n",
    "\n",
    "# drop guest checkouts (no CustomerID)\n",
    "df = df[df['CustomerID'].notna()]\n",
    "print('After removing nulls:', len(df), '(removed', before - len(df), 'rows)')\n",
    "\n",
    "# drop cancellations\n",
    "step = len(df)\n",
    "df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]\n",
    "print('After removing cancellations:', len(df), '(removed', step - len(df), 'rows)')\n",
    "\n",
    "# drop returns and adjustments\n",
    "step = len(df)\n",
    "df = df[df['Quantity'] > 0]\n",
    "print('After removing negative quantity:', len(df), '(removed', step - len(df), 'rows)')\n",
    "\n",
    "# drop zero price rows\n",
    "step = len(df)\n",
    "df = df[df['UnitPrice'] > 0]\n",
    "print('After removing zero price:', len(df), '(removed', step - len(df), 'rows)')\n",
    "\n",
    "# fix data types\n",
    "df['StockCode'] = df['StockCode'].astype(str)\n",
    "df['CustomerID'] = df['CustomerID'].astype(int).astype(str)\n",
    "df['line_total'] = df['Quantity'] * df['UnitPrice']\n",
    "\n",
    "print()\n",
    "print('Final cleaned dataset:', df.shape)\n",
    "print('Customers:', df['CustomerID'].nunique())\n",
    "print('Products:', df['StockCode'].nunique())\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 4. Preprocessing\n",
    "Build a binary user-item matrix. 1 = customer bought that product at least once.\n"]),

code([
    "# group by customer and product, sum quantity, then binarise\n",
    "user_item = (\n",
    "    df.groupby(['CustomerID', 'StockCode'])['Quantity']\n",
    "      .sum()\n",
    "      .unstack(fill_value=0)\n",
    "      .clip(upper=1)\n",
    ")\n",
    "\n",
    "print('User-item matrix shape:', user_item.shape)\n",
    "print('(rows = customers, columns = products)')\n",
    "\n",
    "# density = how many cells are non-zero\n",
    "density = user_item.values.sum() / (user_item.shape[0] * user_item.shape[1])\n",
    "print('Matrix density:', round(density, 4))\n",
    "print('Very sparse - only', round(density * 100, 2), '% of cells are filled')\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 5. Feature Engineering\n",
    "Two things: map products to categories, and build customer-level features.\n"]),

code([
    "# map product descriptions to one of 8 categories using keywords\n",
    "CATEGORY_KEYWORDS = {\n",
    "    'Home Decor':            ['LANTERN','FRAME','CANDLE','VASE','MIRROR','SIGN','CLOCK','LIGHT','HOLDER','WALL'],\n",
    "    'Kitchen & Dining':      ['MUG','CUP','PLATE','BOWL','TEAPOT','JUG','KITCHEN','CAKE','SPOON','JAR'],\n",
    "    'Seasonal & Gifts':      ['CHRISTMAS','XMAS','EASTER','HALLOWEEN','VALENTINE','BIRTHDAY','GIFT','WRAP'],\n",
    "    'Toys & Games':          ['TOY','GAME','PUZZLE','DOLL','BEAR','PLAY','CHILDREN','KIDS'],\n",
    "    'Stationery & Craft':    ['PEN','CARD','NOTEBOOK','CRAFT','PAPER','STAMP','STICKER','TAPE'],\n",
    "    'Fashion & Accessories': ['BAG','SCARF','JEWEL','NECKLACE','BRACELET','PURSE','UMBRELLA','WALLET'],\n",
    "    'Garden & Outdoor':      ['GARDEN','PLANT','OUTDOOR','WATERING','POT','BIRD','FLOWER'],\n",
    "    'Food & Confectionery':  ['FOOD','CHOCOLATE','SWEET','BISCUIT','JAM','HONEY','TEA','COFFEE'],\n",
    "}\n",
    "\n",
    "def assign_category(desc):\n",
    "    if not isinstance(desc, str):\n",
    "        return 'Home Decor'\n",
    "    desc = desc.upper()\n",
    "    for cat, keywords in CATEGORY_KEYWORDS.items():\n",
    "        if any(kw in desc for kw in keywords):\n",
    "            return cat\n",
    "    return 'Home Decor'\n",
    "\n",
    "df['category'] = df['Description'].apply(assign_category)\n",
    "\n",
    "print('Category distribution (transactions):')\n",
    "print(df['category'].value_counts())\n",
]),

code([
    "# plot category distribution\n",
    "cat_counts = df['category'].value_counts()\n",
    "plt.figure(figsize=(9, 4))\n",
    "cat_counts.plot(kind='bar', color='mediumpurple')\n",
    "plt.title('Transactions per Category')\n",
    "plt.xticks(rotation=30, ha='right')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]),

code([
    "# save product-to-category lookup\n",
    "mapping = df[['StockCode','Description','category']].drop_duplicates('StockCode').sort_values('StockCode')\n",
    "mapping.to_csv('data/online+retail/product_categories.csv', index=False)\n",
    "print('Saved product_categories.csv -', len(mapping), 'products')\n",
]),

code([
    "# customer-level features\n",
    "REF_DATE = pd.Timestamp('2011-12-09')\n",
    "\n",
    "def get_segment(n_invoices):\n",
    "    if n_invoices <= 2:\n",
    "        return 'New'\n",
    "    if n_invoices <= 10:\n",
    "        return 'Occasional'\n",
    "    return 'Frequent'\n",
    "\n",
    "def get_price_range(avg_value):\n",
    "    if avg_value < 178.62:\n",
    "        return 'Low'\n",
    "    if avg_value < 293.90:\n",
    "        return 'Mid-Low'\n",
    "    if avg_value < 430.11:\n",
    "        return 'Mid-High'\n",
    "    return 'High'\n",
    "\n",
    "customer_features = df.groupby('CustomerID').agg(\n",
    "    avg_order_value      = ('line_total',  'mean'),\n",
    "    total_invoices       = ('InvoiceNo',   'nunique'),\n",
    "    recency_days         = ('InvoiceDate', lambda x: (REF_DATE - x.max()).days),\n",
    "    favourite_category   = ('category',    lambda x: x.mode()[0]),\n",
    "    purchased_categories = ('category',    lambda x: list(x.unique())),\n",
    "    n_categories         = ('category',    'nunique'),\n",
    ").reset_index()\n",
    "\n",
    "customer_features['customer_segment'] = customer_features['total_invoices'].apply(get_segment)\n",
    "customer_features['price_range']      = customer_features['avg_order_value'].apply(get_price_range)\n",
    "\n",
    "print('Customer segments:')\n",
    "print(customer_features['customer_segment'].value_counts())\n",
    "print()\n",
    "print('Spend tiers:')\n",
    "print(customer_features['price_range'].value_counts())\n",
]),

code([
    "# product catalogue with popularity\n",
    "popularity = (\n",
    "    df.groupby(['StockCode','Description','category'])['CustomerID']\n",
    "      .nunique()\n",
    "      .reset_index(name='popularity_rank')\n",
    ")\n",
    "avg_price = df.groupby('StockCode')['UnitPrice'].mean().reset_index(name='avg_price')\n",
    "product_catalogue = popularity.merge(avg_price, on='StockCode')\n",
    "product_catalogue = product_catalogue.sort_values('popularity_rank', ascending=False).reset_index(drop=True)\n",
    "\n",
    "print('Product catalogue:', len(product_catalogue), 'products')\n",
    "print()\n",
    "print('Top 10 most popular products:')\n",
    "print(product_catalogue.head(10)[['Description','category','popularity_rank']].to_string(index=False))\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 6. Model Training — ALS\n",
    "Using Alternating Least Squares from the implicit library.\n",
    "Chosen after backtesting 6 model types - ALS got HR@5 = 0.3087 vs baseline 0.2250.\n",
    "ALS is made for sparse implicit feedback data like purchase history.\n"]),

code([
    "from scipy.sparse import csr_matrix\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from implicit.als import AlternatingLeastSquares\n",
    "\n",
    "# convert to sparse matrix\n",
    "user_items_sparse = csr_matrix(user_item.values)\n",
    "print('Sparse matrix shape:', user_items_sparse.shape)\n",
    "print('Non-zero entries:', user_items_sparse.nnz)\n",
    "\n",
    "# train ALS\n",
    "# best config found from grid search: factors=50, iterations=50, regularization=1.0\n",
    "print('\\nTraining ALS...')\n",
    "als_model = AlternatingLeastSquares(\n",
    "    factors=50,\n",
    "    iterations=50,\n",
    "    regularization=1.0,\n",
    "    use_gpu=False,\n",
    "    random_state=42\n",
    ")\n",
    "als_model.fit(user_items_sparse)\n",
    "print('Done.')\n",
    "print('User factors:', als_model.user_factors.shape)\n",
    "print('Item factors:', als_model.item_factors.shape)\n",
]),

code([
    "# compute item-item similarity from ALS item factors\n",
    "item_factors = als_model.item_factors\n",
    "item_sim_values = cosine_similarity(item_factors)\n",
    "item_sim_df = pd.DataFrame(\n",
    "    item_sim_values,\n",
    "    index=user_item.columns,\n",
    "    columns=user_item.columns\n",
    ")\n",
    "print('Item similarity matrix:', item_sim_df.shape)\n",
]),

code([
    "# category-category similarity based on item similarity\n",
    "stock_to_cat = (\n",
    "    df[['StockCode','category']]\n",
    "      .drop_duplicates()\n",
    "      .set_index('StockCode')['category']\n",
    ")\n",
    "\n",
    "cat_sim_rows = {}\n",
    "for cat_a in CATEGORY_KEYWORDS:\n",
    "    items_a = stock_to_cat[stock_to_cat == cat_a].index.intersection(item_sim_df.index)\n",
    "    row = {}\n",
    "    for cat_b in CATEGORY_KEYWORDS:\n",
    "        items_b = stock_to_cat[stock_to_cat == cat_b].index.intersection(item_sim_df.columns)\n",
    "        if len(items_a) == 0 or len(items_b) == 0:\n",
    "            row[cat_b] = 0.0\n",
    "        else:\n",
    "            row[cat_b] = float(item_sim_df.loc[items_a, items_b].values.mean())\n",
    "    cat_sim_rows[cat_a] = row\n",
    "\n",
    "category_sim_df = pd.DataFrame(cat_sim_rows).T\n",
    "print('Category similarity matrix:')\n",
    "print(category_sim_df.round(3))\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 7. Evaluation\n",
    "Temporal train/test split - train on orders before Nov 2011, test on after.\n",
    "Metric: Hit Rate@K - did the model recommend something the customer actually bought?\n"]),

code([
    "CUTOFF = pd.Timestamp('2011-11-01')\n",
    "df_train = df[df['InvoiceDate'] < CUTOFF]\n",
    "df_test  = df[df['InvoiceDate'] >= CUTOFF]\n",
    "\n",
    "print('Train set:', df_train.shape)\n",
    "print('Test set: ', df_test.shape)\n",
    "\n",
    "# only evaluate customers who appear in both\n",
    "train_customers = set(df_train['CustomerID'].unique())\n",
    "test_customers  = set(df_test['CustomerID'].unique())\n",
    "eval_customers  = list(train_customers & test_customers)\n",
    "print('Customers in both splits:', len(eval_customers))\n",
]),

code([
    "from implicit.als import AlternatingLeastSquares as ALS\n",
    "\n",
    "# build train matrix\n",
    "ui_train = (\n",
    "    df_train.groupby(['CustomerID', 'StockCode'])['Quantity']\n",
    "            .sum().unstack(fill_value=0).clip(upper=1)\n",
    ")\n",
    "ui_train_sparse = csr_matrix(ui_train.values)\n",
    "\n",
    "# train ALS on train data only\n",
    "als_eval = ALS(factors=50, iterations=50, regularization=1.0, use_gpu=False, random_state=42)\n",
    "als_eval.fit(ui_train_sparse)\n",
    "\n",
    "# item similarity from ALS\n",
    "sim_als = pd.DataFrame(\n",
    "    cosine_similarity(als_eval.item_factors),\n",
    "    index=ui_train.columns, columns=ui_train.columns\n",
    ")\n",
    "\n",
    "# raw cosine baseline\n",
    "sim_raw = pd.DataFrame(\n",
    "    cosine_similarity(ui_train.T.values),\n",
    "    index=ui_train.columns, columns=ui_train.columns\n",
    ")\n",
    "\n",
    "# popularity baseline\n",
    "pop_items = (\n",
    "    df_train.groupby('StockCode')['CustomerID']\n",
    "            .nunique().sort_values(ascending=False).index.tolist()\n",
    ")\n",
    "print('Setup done')\n",
]),

code([
    "def recommend_cf(sim, bought_items, k):\n",
    "    # get items the user hasnt bought yet, scored by similarity\n",
    "    candidates = [sc for sc in sim.columns if sc not in bought_items and sc in sim.columns]\n",
    "    if not candidates:\n",
    "        return []\n",
    "    valid_bought = [sc for sc in bought_items if sc in sim.columns]\n",
    "    if not valid_bought:\n",
    "        return []\n",
    "    scores = sim.loc[candidates, valid_bought].mean(axis=1)\n",
    "    return scores.nlargest(k).index.tolist()\n",
    "\n",
    "def recommend_popular(bought_items, k):\n",
    "    return [p for p in pop_items if p not in bought_items][:k]\n",
    "\n",
    "# run backtest\n",
    "K_values = [1, 3, 5, 10]\n",
    "hits = {'ALS': {k: 0 for k in K_values},\n",
    "        'Raw Cosine': {k: 0 for k in K_values},\n",
    "        'Popularity': {k: 0 for k in K_values}}\n",
    "total = 0\n",
    "\n",
    "for cid in eval_customers:\n",
    "    if cid not in ui_train.index:\n",
    "        continue\n",
    "    bought = ui_train.loc[cid][ui_train.loc[cid] == 1].index.tolist()\n",
    "    actual = df_test[df_test['CustomerID'] == cid]['StockCode'].unique().tolist()\n",
    "    if not bought or not actual:\n",
    "        continue\n",
    "\n",
    "    for k in K_values:\n",
    "        als_recs = recommend_cf(sim_als, bought, k)\n",
    "        raw_recs = recommend_cf(sim_raw, bought, k)\n",
    "        pop_recs = recommend_popular(bought, k)\n",
    "\n",
    "        if any(item in actual for item in als_recs):\n",
    "            hits['ALS'][k] += 1\n",
    "        if any(item in actual for item in raw_recs):\n",
    "            hits['Raw Cosine'][k] += 1\n",
    "        if any(item in actual for item in pop_recs):\n",
    "            hits['Popularity'][k] += 1\n",
    "    total += 1\n",
    "\n",
    "print(f'Evaluated {total} customers')\n",
    "print()\n",
    "print(f'{\"Model\":<18} {\"HR@1\":>6} {\"HR@3\":>6} {\"HR@5\":>6} {\"HR@10\":>6}')\n",
    "print('-' * 45)\n",
    "for model in ['ALS', 'Raw Cosine', 'Popularity']:\n",
    "    row = [f'{hits[model][k]/total:.4f}' for k in K_values]\n",
    "    print(f'{model:<18} {row[0]:>6} {row[1]:>6} {row[2]:>6} {row[3]:>6}')\n",
]),

code([
    "# plot HR@K comparison\n",
    "K_labels = ['HR@1', 'HR@3', 'HR@5', 'HR@10']\n",
    "als_scores = [hits['ALS'][k] / total for k in K_values]\n",
    "raw_scores = [hits['Raw Cosine'][k] / total for k in K_values]\n",
    "pop_scores = [hits['Popularity'][k] / total for k in K_values]\n",
    "\n",
    "x = range(len(K_labels))\n",
    "width = 0.25\n",
    "\n",
    "plt.figure(figsize=(8, 4))\n",
    "plt.bar([i - width for i in x], als_scores, width, label='ALS', color='steelblue')\n",
    "plt.bar([i for i in x],         raw_scores, width, label='Raw Cosine', color='coral')\n",
    "plt.bar([i + width for i in x], pop_scores, width, label='Popularity', color='gray')\n",
    "plt.xticks(list(x), K_labels)\n",
    "plt.ylabel('Hit Rate')\n",
    "plt.title('Hit Rate@K Comparison')\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "print('ALS HR@5 improvement over baseline: +', round((hits[\"ALS\"][5] - hits[\"Raw Cosine\"][5]) / total, 4))\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 8. Save Artefacts\n"]),

code([
    "os.makedirs('models', exist_ok=True)\n",
    "\n",
    "pickle.dump(als_model,         open('models/als_model.pkl',          'wb'))\n",
    "pickle.dump(item_sim_df,       open('models/similarity_matrix.pkl',  'wb'))\n",
    "pickle.dump(product_catalogue, open('models/product_catalogue.pkl',  'wb'))\n",
    "pickle.dump(category_sim_df,   open('models/category_similarity.pkl','wb'))\n",
    "pickle.dump(customer_features, open('models/customer_features.pkl',  'wb'))\n",
    "\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from src.constants import PRODUCT_CATEGORIES\n",
    "enc = LabelEncoder().fit(PRODUCT_CATEGORIES)\n",
    "pickle.dump(enc, open('models/encoder_category.pkl', 'wb'))\n",
    "\n",
    "print('Saved:')\n",
    "for fname in ['als_model.pkl', 'similarity_matrix.pkl', 'product_catalogue.pkl',\n",
    "              'category_similarity.pkl', 'customer_features.pkl', 'encoder_category.pkl']:\n",
    "    size = os.path.getsize(f'models/{fname}') / 1e6\n",
    "    print(f'  {fname:<40} {size:.2f} MB')\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 9. Inference Functions\n",
    "These are used by Member 4 in the integration notebook.\n"]),

code([
    "# reload artefacts\n",
    "item_sim_df       = pickle.load(open('models/similarity_matrix.pkl', 'rb'))\n",
    "product_catalogue = pickle.load(open('models/product_catalogue.pkl', 'rb'))\n",
    "from src.constants import PRODUCT_CATEGORIES\n",
    "\n",
    "\n",
    "def predict_product(user_profile, candidates=None):\n",
    "    \"\"\"\n",
    "    Score categories by similarity to user's purchase history.\n",
    "    Returns list of (category, score) sorted by score descending.\n",
    "    \"\"\"\n",
    "    bought = user_profile['purchase_history']\n",
    "    cats = candidates or PRODUCT_CATEGORIES\n",
    "\n",
    "    if not bought:\n",
    "        raise ValueError('No purchase history. Use find_popular_categories() for cold-start.')\n",
    "\n",
    "    valid_bought = [sc for sc in bought if sc in item_sim_df.columns]\n",
    "    if not valid_bought:\n",
    "        return [(cat, 0.0) for cat in cats]\n",
    "\n",
    "    scores = {}\n",
    "    for cat in cats:\n",
    "        cat_items = product_catalogue[product_catalogue['category'] == cat]['StockCode'].tolist()\n",
    "        valid_items = [sc for sc in cat_items if sc in item_sim_df.index]\n",
    "        if not valid_items:\n",
    "            scores[cat] = 0.0\n",
    "        else:\n",
    "            scores[cat] = float(item_sim_df.loc[valid_items, valid_bought].values.mean())\n",
    "\n",
    "    return sorted(scores.items(), key=lambda x: x[1], reverse=True)\n",
    "\n",
    "\n",
    "def recommend_products(user_profile, category, top_n=3):\n",
    "    \"\"\"\n",
    "    Recommend specific products within a category.\n",
    "    Returns list of dicts: [{category, product, score}, ...]\n",
    "    \"\"\"\n",
    "    bought = user_profile['purchase_history']\n",
    "    valid_bought = [sc for sc in bought if sc in item_sim_df.columns]\n",
    "\n",
    "    cat_items = product_catalogue[product_catalogue['category'] == category].copy()\n",
    "    unowned = cat_items[~cat_items['StockCode'].isin(bought)]\n",
    "\n",
    "    if not valid_bought or unowned.empty:\n",
    "        top = unowned.nlargest(top_n, 'popularity_rank')\n",
    "        return [{'category': category, 'product': row['Description'], 'score': 0.0}\n",
    "                for _, row in top.iterrows()]\n",
    "\n",
    "    valid_unowned = unowned[unowned['StockCode'].isin(item_sim_df.index)].copy()\n",
    "    if valid_unowned.empty:\n",
    "        top = unowned.nlargest(top_n, 'popularity_rank')\n",
    "        return [{'category': category, 'product': row['Description'], 'score': 0.0}\n",
    "                for _, row in top.iterrows()]\n",
    "\n",
    "    valid_unowned['score'] = (\n",
    "        item_sim_df.loc[valid_unowned['StockCode'], valid_bought]\n",
    "                   .mean(axis=1).values\n",
    "    )\n",
    "    top = valid_unowned.nlargest(top_n, 'score')\n",
    "    return [{'category': category, 'product': row['Description'], 'score': round(float(row['score']), 4)}\n",
    "            for _, row in top.iterrows()]\n",
]),

# ─────────────────────────────────────────────────────────────────────────────
md(["## 10. Demo\n",
    "Quick test on the sample profiles.\n"]),

code([
    "from src.constants import SAMPLE_PROFILES\n",
    "\n",
    "for name, profile in SAMPLE_PROFILES.items():\n",
    "    print('=' * 55)\n",
    "    print('Profile:', name)\n",
    "    print('  Segment:', profile['customer_segment'])\n",
    "    print('  Price range:', profile['price_range'])\n",
    "    print('  Purchase history:', len(profile['purchase_history']), 'items')\n",
    "\n",
    "    if not profile['purchase_history']:\n",
    "        print('  Cold-start user - handled by Member 1')\n",
    "        continue\n",
    "\n",
    "    top_cats = predict_product(profile)[:3]\n",
    "    print('  Top categories:')\n",
    "    for cat, score in top_cats:\n",
    "        print(f'    {cat:<28} score={score:.4f}')\n",
    "\n",
    "    print('  Recommended products:')\n",
    "    for cat, score in top_cats:\n",
    "        recs = recommend_products(profile, category=cat, top_n=1)\n",
    "        for r in recs:\n",
    "            print(f'    [{r[\"category\"][:20]:<20}] {r[\"product\"][:40]:<40} {r[\"score\"]:.4f}')\n",
]),

]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

out = os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'ml_model.ipynb')
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written: {os.path.abspath(out)}")
print(f"Cells: {len(cells)}")
