# =============================================================================
# search_module.py
# BFS-based product category search — CIC6314 Smart Product Recommendation
#
# Member 1 (Issye) — feature/search branch
#
# PUBLIC INTERFACE:
#   find_reachable_categories(user_profile, eligible, max_hops=2, threshold=0.05)
#       → list[str]  — BFS from favourite_category on 8×8 ALS similarity graph
#   find_popular_categories(eligible, price_range, top_n=3)
#       → list[tuple[str, int]]  — cold-start fallback, ranked by buyer count
#
# REQUIRES: models/category_similarity.pkl, models/product_catalogue.pkl
#           (generated by running notebooks/ml_model.ipynb)
# =============================================================================

import pickle
import os

# ── path resolution ───────────────────────────────────────────────────────────
# Works whether called from repo root or from src/
_HERE    = os.path.dirname(os.path.abspath(__file__))
_ROOT    = os.path.join(_HERE, '..')
_CAT_SIM = os.path.join(_ROOT, 'models', 'category_similarity.pkl')
_PROD_CAT= os.path.join(_ROOT, 'models', 'product_catalogue.pkl')

# ── lazy loaders (load pkl once, cache in module scope) ───────────────────────
_cat_sim_cache  = None
_prod_cat_cache = None

def _load_cat_sim():
    global _cat_sim_cache
    if _cat_sim_cache is None:
        _cat_sim_cache = pickle.load(open(_CAT_SIM, 'rb'))
    return _cat_sim_cache

def _load_prod_cat():
    global _prod_cat_cache
    if _prod_cat_cache is None:
        _prod_cat_cache = pickle.load(open(_PROD_CAT, 'rb'))
    return _prod_cat_cache


# =============================================================================
# FUNCTION 1 — find_reachable_categories
# Used by: personalised path (returning customers with purchase history)
# =============================================================================

def find_reachable_categories(
    user_profile: dict,
    eligible:     list,
    max_hops:     int   = 2,
    threshold:    float = 0.06,   # tuned to ALS-derived similarity scale (0.03–0.19)
) -> list:
    """
    BFS traversal of the 8×8 ALS category similarity graph.

    Starting from the customer's favourite_category, follow edges whose
    similarity exceeds `threshold`, collecting categories that are both
    reachable within `max_hops` AND present in `eligible`.

    Parameters
    ----------
    user_profile : dict  — must contain 'favourite_category' key
    eligible     : list  — categories allowed by the rules engine (apply_rules output)
    max_hops     : int   — maximum BFS depth (default 2)
    threshold    : float — minimum similarity to traverse an edge (default 0.05)
                           NOTE: ALS cosine similarity values in this dataset are in
                           the range 0.03–0.19 (not 0–1). Threshold 0.06 is chosen
                           because Fashion & Accessories max similarity is 0.059 —
                           below this threshold it is correctly pruned from all paths,
                           matching its real-world isolation from home/kitchen/garden.

    Returns
    -------
    list[str] — subset of eligible, ordered by BFS discovery (closest first).
                Returns eligible unchanged if favourite_category is None.
    """
    start = user_profile.get('favourite_category')

    # cold-start guard: no favourite means no graph anchor → return eligible as-is
    if not start:
        return list(eligible)

    cat_sim = _load_cat_sim()

    visited = {start}
    queue   = [(start, 0)]          # (category, hops_from_start)
    result  = [start] if start in eligible else []

    while queue:
        node, hops = queue.pop(0)

        if hops >= max_hops:
            continue

        # sort neighbours by similarity descending, traverse only above threshold
        row = cat_sim[node].drop(node).sort_values(ascending=False)
        for neighbour, sim in row.items():
            if sim < threshold:
                break                   # sorted desc — no need to continue
            if neighbour not in visited:
                visited.add(neighbour)
                if neighbour in eligible:
                    result.append(neighbour)
                queue.append((neighbour, hops + 1))

    # fallback: if BFS pruned everything, return full eligible list
    return result if result else list(eligible)


# =============================================================================
# FUNCTION 2 — find_popular_categories
# Used by: cold-start path (new customers with no purchase history)
# =============================================================================

def find_popular_categories(
    eligible:    list,
    price_range: str,
    top_n:       int = 3,
) -> list:
    """
    Return the most globally purchased categories within the eligible set.

    Uses popularity_rank (unique buyer count per product) from product_catalogue.
    Scores are integer buyer counts — Member 4's display layer renders them as
    "X buyers" rather than probabilities.

    Parameters
    ----------
    eligible    : list — categories allowed by apply_rules()
    price_range : str  — "Low" | "Mid-Low" | "Mid-High" | "High" (reserved for
                         future price-tier filtering; currently ranks all eligible)
    top_n       : int  — number of categories to return (default 3)

    Returns
    -------
    list[tuple[str, int]] — [(category, buyer_count), ...] sorted descending.
    """
    catalogue = _load_prod_cat()

    counts = (
        catalogue[catalogue['category'].isin(eligible)]
        .groupby('category')['popularity_rank']
        .sum()
        .sort_values(ascending=False)
    )

    return [(cat, int(count)) for cat, count in counts.head(top_n).items()]
