# =============================================================================
# search_module.py
# A*-based product category search — CIC6314 Smart Product Recommendation
#
# Member 1 (Issye) — feature/search branch
#
# PUBLIC INTERFACE:
#   find_reachable_categories(user_profile, eligible, max_hops=2, threshold=0.06)
#       → list[str]  — A* search from favourite_category on 8×8 ALS similarity
#                      graph, ordered by f-score (g + h)
#   find_popular_categories(eligible, price_range, top_n=3)
#       → list[tuple[str, int]]  — cold-start fallback, ranked by buyer count
#
# A* PROBLEM FORMULATION:
#   State space   : 8 product categories (graph nodes)
#   Initial state : user's favourite_category
#   Goal          : eligible categories within max_hops
#   Edge cost g   : 1 − sim(u, v)   [high similarity → low cost → preferred path]
#   Heuristic h   : 1 − normalised_popularity(n)   [admissible: popular cats are
#                   more desirable; h ∈ [0,1], never overestimates true cost]
#   f(n)          : g(n) + h(n)   [A* minimises f — balances graph proximity
#                   with estimated category desirability]
#
# REQUIRES: models/category_similarity.pkl, models/product_catalogue.pkl
#           (generated by running notebooks/ml_model.ipynb)
# =============================================================================

import heapq
import pickle
import os

# ── path resolution ───────────────────────────────────────────────────────────
# Works whether called from repo root or from src/
_HERE    = os.path.dirname(os.path.abspath(__file__))
_ROOT    = os.path.join(_HERE, '..')
_CAT_SIM = os.path.join(_ROOT, 'models', 'category_similarity.pkl')
_PROD_CAT= os.path.join(_ROOT, 'models', 'product_catalogue.pkl')

# ── lazy loaders (load pkl once, cache in module scope) ───────────────────────
_cat_sim_cache  = None
_prod_cat_cache = None

def _load_cat_sim():
    global _cat_sim_cache
    if _cat_sim_cache is None:
        _cat_sim_cache = pickle.load(open(_CAT_SIM, 'rb'))
    return _cat_sim_cache

def _load_prod_cat():
    global _prod_cat_cache
    if _prod_cat_cache is None:
        _prod_cat_cache = pickle.load(open(_PROD_CAT, 'rb'))
    return _prod_cat_cache


# =============================================================================
# FUNCTION 1 — find_reachable_categories
# Used by: personalised path (returning customers with purchase history)
# =============================================================================

def find_reachable_categories(
    user_profile: dict,
    eligible:     list,
    max_hops:     int   = 2,
    threshold:    float = 0.06,   # tuned to ALS-derived similarity scale (0.03–0.19)
) -> list:
    """
    A* search on the 8×8 ALS category similarity graph.

    Problem Formulation
    -------------------
    State space   : 8 product categories as graph nodes
    Initial state : user's favourite_category
    Goal          : any eligible category reachable within max_hops
    Edge cost g   : 1 − sim(u, v)   [higher similarity → lower cost → preferred]
    Heuristic h   : 1 − normalised_popularity(n)
                    Admissible because normalised_popularity ∈ [0, 1], so h ∈ [0, 1],
                    and every edge cost is > 0, meaning h never overestimates the
                    true remaining cost to any goal node.
    f(n)          : g(n) + h(n)   — A* minimises f, producing an ordering that
                    balances graph proximity (g) with category desirability (h).

    ALS cosine similarity values in this dataset range from 0.03 to 0.19 (not 0–1),
    shaped by purchase sparsity. Threshold 0.06 is calibrated to this scale:
    Fashion & Accessories' maximum off-diagonal similarity is 0.059, so it is
    correctly isolated from all traversal paths at this threshold.

    Parameters
    ----------
    user_profile : dict  — must contain 'favourite_category' key
    eligible     : list  — categories allowed by apply_rules()
    max_hops     : int   — maximum search depth from initial state (default 2)
    threshold    : float — minimum edge similarity to traverse (default 0.06)

    Returns
    -------
    list[str] — eligible categories ordered by A* f-score (lowest = most optimal).
                Falls back to full eligible list if start is None or A* finds nothing.
    """
    start = user_profile.get('favourite_category')

    # cold-start guard: no favourite_category means no initial state → return as-is
    if not start:
        return list(eligible)

    cat_sim  = _load_cat_sim()
    prod_cat = _load_prod_cat()

    # ── Admissible heuristic: h(n) = 1 − normalised_popularity(n) ───────────
    # Popular categories (many unique buyers) have low h, so A* reaches them
    # sooner among nodes at equal path cost.  Normalised to [0, 1] → admissible.
    pop     = prod_cat.groupby('category')['popularity_rank'].sum()
    max_pop = float(pop.max()) if pop.max() > 0 else 1.0
    h_val   = {cat: 1.0 - float(pop.get(cat, 0)) / max_pop
               for cat in cat_sim.columns}

    # ── A* open set: (f, g, depth, node) ────────────────────────────────────
    h_start  = h_val.get(start, 1.0)
    open_set = [(h_start, 0.0, 0, start)]   # f=h(start) since g=0 at initial state
    settled  = {}              # node → lowest g cost at which it was settled
    results  = []              # (f_score, category) for each eligible node found

    while open_set:
        f, g, depth, node = heapq.heappop(open_set)

        # Skip if already settled via a cheaper path (standard A* duplicate check)
        if node in settled and settled[node] <= g:
            continue
        settled[node] = g

        # Record eligible nodes (including the initial state if eligible)
        if node in eligible:
            results.append((f, node))

        # Do not expand beyond max_hops
        if depth >= max_hops:
            continue

        # Expand neighbours in descending similarity order; break below threshold
        row = cat_sim[node].drop(node).sort_values(ascending=False)
        for neighbour, sim in row.items():
            if sim < threshold:
                break                          # sorted desc — safe to stop here
            if neighbour in settled:
                continue
            g_new = g + (1.0 - sim)           # edge cost: 1 − similarity
            f_new = g_new + h_val.get(neighbour, 1.0)
            heapq.heappush(open_set, (f_new, g_new, depth + 1, neighbour))

    # Sort by A* f-score — lowest f = most optimal (closest + most popular)
    results.sort(key=lambda x: x[0])
    ordered = [cat for _, cat in results]

    # Fallback: if A* found nothing eligible, return full eligible list
    return ordered if ordered else list(eligible)


# =============================================================================
# FUNCTION 2 — find_popular_categories
# Used by: cold-start path (new customers with no purchase history)
# =============================================================================

def find_popular_categories(
    eligible:    list,
    price_range: str,
    top_n:       int = 3,
) -> list:
    """
    Return the most globally purchased categories within the eligible set.

    Uses popularity_rank (unique buyer count per product) from product_catalogue.
    Scores are integer buyer counts — Member 4's display layer renders them as
    "X buyers" rather than probabilities.

    Parameters
    ----------
    eligible    : list — categories allowed by apply_rules()
    price_range : str  — "Low" | "Mid-Low" | "Mid-High" | "High" (reserved for
                         future price-tier filtering; currently ranks all eligible)
    top_n       : int  — number of categories to return (default 3)

    Returns
    -------
    list[tuple[str, int]] — [(category, buyer_count), ...] sorted descending.
    """
    catalogue = _load_prod_cat()

    counts = (
        catalogue[catalogue['category'].isin(eligible)]
        .groupby('category')['popularity_rank']
        .sum()
        .sort_values(ascending=False)
    )

    return [(cat, int(count)) for cat, count in counts.head(top_n).items()]
